_target_: method.AbundancePlotConfig

label: abundance plot
name: Generate abundance plots

barcolor : condition
axisx : timepoint
axisx_labeltilt : 70 # 0 is no tilt
height_each_subfig: !!float 5.5
palette: 'pastel'

x_text_modify_as: null # or a list of float, int or str, e.g ['0h', '4h'] or [0, 4] according to the x ticks
as_grid : False
