_target_: method.MeanEnrichmentLinePlotConfig

label: mean-enrichment-line-plot
name: Generate Mean Enrichment line plots

color_lines_by: condition # condition|metabolite
palette_condition: muted # seaborn/matplotlib palette. Has effect if color_lines_by condition
palette_metabolite: auto_multi_color # auto_multi_color|PATH_TO_COLOR.csv.  Has effect if color_lines_by metabolite
xaxis_title: Time # Days|Hours|Minutes|Seconds|Time ...
alpha: 1  # 0 for transparent, 1 max intensity
plot_grouped_by_dict : null # cell : 0 : [Cit, Iso-cit] will display both in same plane
height_subplot: !!float 4.8
as_grid : False
