_target_: method.MultiGroupComparisonConfig

label: multi group
name: Multi group statistical comparison using Kruskal-Wallis test

#grouping :
#  - condition
#  - timepoint

#correction_method : "bonferroni"

datatypes:
  - abundances
  - mean_enrichment # same as fractional_contributions
  - isotopologues
  - isotopologue_proportions

#impute_values:
#  abundances: "min"
#  mean_enrichment: "min"
#  isotopologues: "min"
#  isotopologue_proportions: "min"
