_target_: method.PcaAnalysisConfig

label: pca-analysis-tables
name: Generate Principal Component Analysis tables

# Always runs a global pca (whole dataset).
# In addition, pca_split_further:
#   possibility to run pca on split datasets. Set null if none desired
pca_split_further:
  - timepoint
  # - condition

