categories:
    - Visualization
long_description: |
    Galaxy Charts is a visualization tool available as plugin for Galaxy.
    Certain chart types like e.g. Histograms, pre-process data before rendering the visualization.
    The pre-processing is done by this tool. Noteworthy, many chart types like e.g. Bar diagrams and Scatterplots, do not require data pre-processing.
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/charts
homepage_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/charts/
type: unrestricted
name: charts
description:  Enables advanced visualization options in Galaxy Charts
