name: galaxy-build
channels:
  - conda-forge
  - bioconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2024.12.14=hf0a4a13_0
  - libffi=3.4.2=h3422bc3_5
  - liblzma=5.6.3=h39f12f2_1
  - libsqlite=3.48.0=h3f77e49_1
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_2
  - openssl=3.4.0=h81ee809_1
  - pip=24.3.1=pyh8b19718_2
  - python=3.10.16=h870587a_1_cpython
  - readline=8.2=h92ec313_1
  - setuptools=75.8.0=pyhff2d567_0
  - tk=8.6.13=h5083fa2_1
  - tzdata=2025a=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - allure-python-commons==2.13.5
      - annotated-types==0.7.0
      - argcomplete==3.5.3
      - async-timeout==5.0.1
      - attrs==24.3.0
      - bioblend==1.4.0
      - bleach==6.2.0
      - boltons==24.1.0
      - cachecontrol==0.14.2
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - cheetah3==3.2.6.post1
      - click==8.1.8
      - coloredlogs==15.0.1
      - conda-package-streaming==0.11.0
      - cwl-upgrader==1.2.12
      - cwl-utils==0.36
      - cwltool==3.1.20250110105449
      - distlib==0.3.9
      - docutils==0.21.2
      - edam-ontology==1.25.2
      - ephemeris==0.10.10
      - filelock==3.17.0
      - frozenlist==1.5.0
      - future==1.0.0
      - galaxy-tool-util==24.1.4
      - galaxy-util==24.1.4
      - glob2==0.7
      - gxformat2==0.20.0
      - h5py==3.12.1
      - humanfriendly==10.0
      - idna==3.10
      - isodate==0.7.2
      - jinja2==3.1.5
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mistune==3.0.2
      - msgpack==1.1.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - networkx==3.4.2
      - numpy==2.2.2
      - oyaml==1.0
      - packaging==24.2
      - pathvalidate==3.2.3
      - pillow==11.1.0
      - planemo==0.75.26
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - propcache==0.2.1
      - prov==1.5.1
      - psutil==6.1.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydot==2.0.0
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pysam==0.22.1
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - rdflib==7.1.3
      - repoze-lru==0.7
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rich-argparse==1.6.0
      - routes==2.5.1
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - schema-salad==8.8.20241206093842
      - six==1.17.0
      - sortedcontainers==2.4.0
      - spython==0.3.14
      - tabulate==0.9.0
      - tifffile==2025.1.10
      - tinydb==4.8.2
      - tuspy==1.1.0
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - virtualenv==20.29.1
      - webencodings==0.5.1
      - yarl==1.18.3
      - zipstream-new==1.1.8
      - zstandard==0.23.0
prefix: /opt/homebrew/anaconda3/envs/galaxy-build
