name: Galaxy Tool Linting and Tests for push and PR
# Fallback workflow that provides a succeeding "Check workflow success" job
# as this is a requirement for being able to merge a PR
# see https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
on:
  pull_request:
concurrency:
  # Group runs by PR, but keep runs on the default branch separate
  # because we do not want to cancel ToolShed uploads
  group: pr-${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') && github.run_number || github.ref }}
  cancel-in-progress: true
jobs:
  determine-success:
    name: Check workflow success
    runs-on: ubuntu-latest
    steps:
      -  run: 'echo "No tool tests required for this PR"
