name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        if: github.repository_owner == 'galaxyproject'
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          config: >
            [
              {
                "command": "run-all-tool-tests",
                "issue_type": "issue"
              }
              {
                "command": "update-test-data",
                "permission": "write",
                "issue_type": "pull-request"
              }
            ]
